name: Pull request

on:
  pull_request:

jobs:
  check-pr-title:      
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: ^(build|ci|docs|feat|fix|perf|refactor|test)(\(.*?\))?:\ .*$

  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci --unsafe-perm
          npm run build
